### ISSUE TITLE
Prepare version 3.0.0

### ISSUE THREAD

**Issue by adorade** [adorade/gulp-stylelint-esm#39]
- [x] better error handling #30 
- [x] better format output #31 
- [x] better autofix option #32 
- [x] better debug information #33
